pipeline{
    agent any
    stages{
        stage('Compile bank.py'){
            steps{
                cd com/beehyv
                python bank.py
            }

        }
        stage('Compile calculator.py'){
            steps{
                cd com/beehyv
                python calculator.py
            }

        }
        stage('Compile employee.py'){
            steps{
                cd com/beehyv
                python employee.py
            }

        }
        stage('testing'){
            steps{
                cd unit-test-practice
                python -m {unittest}
            }

        }

    }

}
