pipeline{
	agent any
    stages{
    	stage('Compile stage of bank.py'){
        	steps{
            	cd com/beehyv
                python bank.py
            }
        }
        stage('Compile stage of calculator.py'){
        	steps{
				cd com/beehyv
			    python calculator.py
			}
		}
		stage('Compile stage of employee.py'){
			steps{
				cd com/beehyv
				python employee.py
			}
		}
	}
}
